#!/usr/bin/env bash
# installs and configures HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLE=0/ENABLE=1/'/etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 355-web-01 34.74.59.91:80 check\n\tserver 355-web-02 34.204.179.254:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start