#!/usr/bin/env bash
# displays Best School 10 times but displays Best School and hi on 9th iteration

COUNTER=0
while [ "$COUNTER" -lt 10 ]; do
      echo "Best School"
      if [ "$COUNTER" -eq 8 ]
      then
	echo "Hi"
      fi
      let COUNTER=COUNTER+1
done

	