#!/usr/bin/env bash
# Configures ufw to block all incomining traffic exceprt certain TCP ports
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
